### ISSUE TITLE
Change relative path of img/ assets to ../img/

### ISSUE THREAD

**Issue by korenmiklos** [datacarpentry/stata-economics#4]

**Comment by fmichonneau** [comment]
hi @korenmiklos, it's best to use the `{% link %}` [Jekyll command](https://jekyllrb.com/docs/liquid/tags/#linking-to-posts) for the file paths instead of hard-coding relative paths. In addition, because we try to make our lesson website offline-capable, we need to prepend `{{ relative_root_path }}` to these paths. 

For instance, for the image `pwd.png` you would include it in the episode as:

```
![working directory]({{ relative_root_path }}{% link img/pwd.png %})
```

let me know if you have any questions or if you'd like me to review the code.

**Comment by ErinBecker** [comment]
Thanks @fmichonneau! I wasn't aware of this and will add it to my mental note when reviewing our other lessons in the future!

**Comment by korenmiklos** [comment]
`relative_root_path` seems to point to `https://datacarpentry.org/`, not `https://datacarpentry.org/stata-economics/`. I will try to set base url
